### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [peterdanis/wrapbox#66]
```
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-7058/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
Parent pid 7058, child pid 7062
Parent is shutting down, bye...
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/617

**Comment by peterdanis** [comment]
Thanks for letting me know.

Solved by ce05242c64227ab3f66dd9c24706cbc402a0ef3f
